# Generated by Django 4.2.5 on 2023-10-15 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(related_name='invitations', to='planner.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planner.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(related_name='fulfilled_by', to='planner.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='planner.event'),
        ),
    ]
